### ISSUE TITLE
Wrong cast is requested from Eigen - build failed  

### ISSUE THREAD

**Issue by nhershko** [arpg/vicalib#36] opened 2017-01-19 07:28 UTC
Hi,
I'm trying to build the calibration tool and have issue when trying to include Eigen headers.
I got the below issue:
> /home/user/git/VI/vicalib/src/vicalib-engine.cc:581:1:   required from here
> /usr/include/eigen3/Eigen/src/Core/MathFunctions.h:367:9: error: invalid static_cast from type ‘const ceres::Jet<double, 19>’ to type ‘int’

This issue is raised though Eigen is built successfully and well included to another projects. 
Thanks!

P.S.
I've tried with few GCC versions: 4.9, 4.8, 5.4, 6.2

**Comment by crheckman** [comment] 2017-02-08 20:21
Are you sure your ceres is built from source and using the same version as eigen? It seems that the problem is with ceres here, not vicalib?

**Comment by crheckman** [comment] 2018-10-24 14:51
No comment in awhile and none of us have seen this since; closing.

**Closed by crheckman** 2018-10-24 14:51 UTC
