### ISSUE TITLE
Vicalib fully installed along with dependencies but wont run due to 'logtostderr' flag error

### ISSUE THREAD

**Issue by RoboBAR** [arpg/vicalib#40] opened 2018-10-24 13:10 UTC
Hi,

Vicalib is fully built and installed along with all its dependencies, however, unfortunately i cant run it. 
i keep getting an error whenever i try any "vicalib" command in the terminal, here is the message:

"ERROR: something wrong with flag 'logtostderr' in file '...glog/src/logging.cc'.  One possibility: file '.../glog/src/logging.cc' is being linked both statically and dynamically into this executable."

i did my (googling) research and came up empty.
here is what i have tried: 
i removed and re-built/installed gflags and glog using ccmake, make, make install. 
Then i re-built/installed vicalib, unfortunately the problem persists. 
This might not be an issue with vicalib but rather one of its dependencies, however id seriouslly appreciate any help as i am desprate to solve this and start using vicalib.

Thanks for any dispensed advice,
CajaYairB

**Comment by crheckman** [comment] 2018-10-24 13:53
This is not a problem with vicalib but is due to your build environment. We've seen this come up when one of your deps are built against a static glog and another is built against dynamic glog.

Trouble is when you build a static library it is subsumed by the downstream packages, making this problem particularly difficult to address and requiring removal and rebuild of packages that subsumed the offending binary.

Your fix is unfortunately to find which one is building against static glog and then rebuild it against dynamic glog. If you built Node, that could be what's causing this error. I'd remove Node and rebuild HAL, etc.

**Comment by CajaYairB** [comment] 2018-10-24 14:35
Thank you Chris your response is greatly appreciated. 
Indeed I installed Node, I will try your suggestion and get back to you. 
But basically if I understood you correctly,you are saying that one or more of the packages that is/are dependent on glog is/are causing this problem because it/they was/were linked statically. 

Then I guess the most important question right now is:
how would i know that i'm not linking any reinstalled packages to the dynamic glog library once again? do you know of such an option to set in ccmake? or perhaps it would be some field in the cmake file, or cmakelists? If it is set somewhere in the souce code or the generated build files then perhaps i can go over those files and figure out who the offending package/s is/are.

**Comment by crheckman** [comment] 2018-10-24 14:47
You may have two versions of glog (static and dynamic) on your device. Ensure the packages you're building are linking to the dynamic libs, and to save yourself this pain in the future, build these libraries as dynamic libs too. That's an option in ccmake as `BUILD_SHARED_LIBS`.

If you have the two versions of glog installed, I would recommend removing the static one. There's no easy way to see if cmake is creating makefiles to link your library against the static version, but there is a hack: `grep -ri '\-lglog' *` in your build dirs for the library you're creating; I usually do this to debug deep cmake related problems.

Other approaches e.g. `ldd [libraryname].so` doesn't work since static libraries don't show up in it; you'd have to actually go and run `nm` or some other symbol exposing utility on the resulting binary and see if symbols from the static library are present in the new binary.

**Comment by crheckman** [comment] 2018-10-24 14:49
Closing this issue as it's not a bug with vicalib but a problem with the user's build environment.

**Closed as completed by crheckman** 2018-10-24 14:49 UTC
